final Map<String, Map<String, String>> localizedStrings = {
  'it': {
    'title': 'Comando Ascensore',
    'floor': 'Piano attuale',
    'moving': 'Ascensore in movimento...',
    'emergency': 'EMERGENZA! 🚨',
    'emergencyMessage': 'Campanello di emergenza attivato.',
    'close': 'Chiudi',
    'settings': 'Impostazioni',
    'user': 'Utente',
    'audio': 'Audio',
    'vibration': 'Vibrazione',
    'darkTheme': 'Tema scuro',
    'language': 'Lingua',
    'ipAddress': 'Indirizzo IP',
    'save': 'Salva',
    'cancel': 'Annulla',
  },
  'en': {
    'title': 'Elevator Control',
    'floor': 'Current floor',
    'moving': 'Elevator moving...',
    'emergency': 'EMERGENCY! 🚨',
    'emergencyMessage': 'Emergency bell activated.',
    'close': 'Close',
    'settings': 'Settings',
    'user': 'User',
    'audio': 'Audio',
    'vibration': 'Vibration',
    'darkTheme': 'Dark theme',
    'language': 'Language',
    'ipAddress': 'IP Address',
    'save': 'Save',
    'cancel': 'Cancel',
  },
  'es': {
    'title': 'Control del Ascensor',
    'floor': 'Piso actual',
    'moving': 'Ascensor en movimiento...',
    'emergency': '¡EMERGENCIA! 🚨',
    'emergencyMessage': 'Timbre de emergencia activado.',
    'close': 'Cerrar',
    'settings': 'Configuración',
    'user': 'Usuario',
    'audio': 'Audio',
    'vibration': 'Vibración',
    'darkTheme': 'Tema oscuro',
    'language': 'Idioma',
    'ipAddress': 'Dirección IP',
    'save': 'Guardar',
    'cancel': 'Cancelar',
  },
  'fr': {
    'title': 'Contrôle de l\'Ascenseur',
    'floor': 'Étage actuel',
    'moving': 'Ascenseur en mouvement...',
    'emergency': 'URGENCE! 🚨',
    'emergencyMessage': 'Sonnette d\'urgence activée.',
    'close': 'Fermer',
    'settings': 'Paramètres',
    'user': 'Utilisateur',
    'audio': 'Audio',
    'vibration': 'Vibration',
    'darkTheme': 'Thème sombre',
    'language': 'Langue',
    'ipAddress': 'Adresse IP',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
  },
  'de': {
    'title': 'Aufzugssteuerung',
    'floor': 'Aktueller Stock',
    'moving': 'Aufzug in Bewegung...',
    'emergency': 'NOTFALL! 🚨',
    'emergencyMessage': 'Notrufknopf aktiviert.',
    'close': 'Schließen',
    'settings': 'Einstellungen',
    'user': 'Benutzer',
    'audio': 'Audio',
    'vibration': 'Vibration',
    'darkTheme': 'Dunkles Thema',
    'language': 'Sprache',
    'ipAddress': 'IP-Adresse',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
  },
};
